DO $$
DECLARE
    sequence_name TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'controle_versoes'::regclass AND attname = 'id' AND attidentity <> ''
    ) THEN
        ALTER TABLE controle_versoes ALTER COLUMN id TYPE BIGINT;
        ALTER TABLE controle_versoes ALTER COLUMN id DROP DEFAULT;
        ALTER TABLE controle_versoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        SELECT pg_get_serial_sequence('controle_versoes', 'id') INTO sequence_name;
        EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(id) FROM controle_versoes), 0) + 1, false)', sequence_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'controle_versoes'::regclass AND attname = 'versao' AND attidentity <> ''
    ) THEN
        ALTER TABLE controle_versoes ALTER COLUMN versao TYPE BIGINT;
        ALTER TABLE controle_versoes ALTER COLUMN versao DROP DEFAULT;
        ALTER TABLE controle_versoes ALTER COLUMN versao ADD GENERATED BY DEFAULT AS IDENTITY;
        SELECT pg_get_serial_sequence('controle_versoes', 'versao') INTO sequence_name;
        EXECUTE format('SELECT setval(%L, COALESCE((SELECT MAX(versao) FROM controle_versoes), 0) + 1, false)', sequence_name);
    END IF;
END $$;
